Hw1 implementation
anatolyburtsev/MADE_JAVA_HW1 pull request #1
Opened 2019-10-14 17:36 UTC by anatolyburtsev

2019-10-14 19:20 UTC, alexmatorin requested changes

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Main.java
> +        Service service = Service.builder()
тут билдер излишен, лучше просто конструктор

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Service.java
> +
удалить пустую строку

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/exceptions/IncorrectInputDataException.java
> +public class IncorrectInputDataException extends RuntimeException {
свои ексепшены тут не нужны, можно кидать стандартные

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/model/TradeType.java
> +    FX_SPOT, BOND, COMMODITY_SPOT, IR_SWAP
лучше каждый елемент на новой строке

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    private final Integer price;
если поле nonNull, то лучше int

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    public AbstractTrade(Integer price) {
можно @RequiredArgConstructor

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach2/model/ITradeCreator.java
> +public interface ITradeCreator {
венгерская нотация в java не используется. убрать i

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +    private final Integer price;
заменить на int

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +@Value
если используется @Value, то можно убрать private final с полей

2019-10-14 19:20 UTC, alexmatorin commented on build.gradle
> +    testImplementation('org.junit.jupiter:junit-jupiter:5.5.+')
лучше никогда не использовать + в версии, чтобы билды были воспроизводимы

2019-10-14 19:20 UTC, alexmatorin commented on build.gradle
> +sourceCompatibility = 1.12
просто 12

2019-10-14 19:20 UTC, alexmatorin commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-all.zip
какая-то очень старая версия указана

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach2/ConverterEnhanced.java
> +public class ConverterEnhanced {
Можно было вынести интерфейс TradeConverter и сделать 2 реализации.
Класс Main и Service вынести из пакета approach1

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach2/model/ITradeCreator.java
> +package ca.trade.approach2.model;
не понятно по какому принципы сгруппированы классы в пакете approach1 и approach2

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Service.java
> +public class Service {
Лучше избегать слишком общих названий, поменять имя хотя-бы на TradeService или TradeConversionService
и вынести интерфейс

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Converter.java
> +public class Converter {
слишком общее название класса

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Converter.java
> +    public AbstractTrade convertApiToData(TradeDefinition tradeDefinition) {
не понятно что значит APi в названии, Лучше класс назвать TradeConverter, а метод convert

2019-10-14 19:20 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Converter.java
> +    public AbstractTrade convertApiToData(TradeDefinition tradeDefinition) {
лучше удалить класс Converter, данный метод перенести в TradeDefinition, и назвать toTrade, получится в объектно-ориентированном стиле, и все поля TradeDefinition можно сделать private

2019-10-14 19:20 UTC, alexmatorin commented on src/test/java/ca/trade/ConverterTest.java
> +    void testConvert_abstractValidData_success() {
если у Convert и ConverterEnhanced вынести интерфейс, то можно избавится от копипаста

2019-10-14 19:20 UTC, alexmatorin commented on src/test/java/ca/trade/TradeTestFixture.java
> +public class TradeTestFixture {
лучше удалить этот класс, понимания он не добавляет

2019-10-14 19:20 UTC, alexmatorin commented on src/test/java/ca/trade/ConverterTest.java
> +    void testConvert_nonAbstractValidData_success() {
в тестах лучше использовать стандартный java naming convention. _ не использовать

2019-10-14 19:20 UTC, alexmatorin commented on src/test/java/ca/trade/TradeTestFixture.java
> +}
по хорошему надо проверить все реализации ITradeCreator. Возможно где-то возвращается класс не того типа.
Также нет теста для класса Service

2019-10-14 19:20 UTC, alexmatorin commented on src/test/java/ca/trade/TradeTestFixture.java
> +}
В целом решение хорошее

2019-10-14 22:29 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/Main.java
> +        Service service = Service.builder()
Сейчас, пока только два аргумента, да. Но их количество может вырости и как правило это приводит к конструктору с 5+ параметрами. Поэтому имеет смысл сразу использовать Builder, дабы избежать трудностей в будущем.

2019-10-14 22:30 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/Service.java
> +
ок

2019-10-14 22:37 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/exceptions/IncorrectInputDataException.java
> +public class IncorrectInputDataException extends RuntimeException {
Пользователям этого модуля будет удобней перехватывать кастомные исключения, чтобы по разному их обрабывать. Например, разные сообщения об ошибках показывать на фронте. Можно, конечно, напрямую exception message показывать пользователю, но в таком случае возникают сложности с поддержкой разных языков.

2019-10-14 22:38 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/exceptions/IncorrectInputDataException.java
> +public class IncorrectInputDataException extends RuntimeException {
Просто IOException может гипотетически в нескольки местах возникнуть, а свои исключения дают большую гранулярность

2019-10-14 22:38 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/model/TradeType.java
> +    FX_SPOT, BOND, COMMODITY_SPOT, IR_SWAP
ок

2019-10-14 22:41 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    private final Integer price;
Такая замена может привести к потенциальной проблеме. Когда экземпляр этого класса создан, а цена не задана, тогда она explicit будет выставлена в 0. Лучше fail fast, чем такое потенциально опасное поведение

2019-10-14 22:43 UTC, anatolyburtsev commented on src/test/java/ca/trade/ConverterTest.java
> +    void testConvert_nonAbstractValidData_success() {
Мне нравится такой подход, в случае тестов нас больше интересует читаемость, когда по названию теста хочется понять что именно упало. И я использую вот такой трехкомпонентный подход: testНазваниеМетодаДляТеста_краткоеОписание_{success или ожидаемый Exception}

2019-10-14 22:44 UTC, anatolyburtsev commented on src/test/java/ca/trade/TradeTestFixture.java
> +public class TradeTestFixture {
Это пока так мало тестов, да. Но опять же, лучше сразу завести класс, где создаются тестовые данные, чем потом из кучи тестов вытаскивать их все в одно место, попутно все починяя.

2019-10-14 22:46 UTC, anatolyburtsev commented on src/test/java/ca/trade/ConverterTest.java
> +    void testConvert_abstractValidData_success() {
Можно, но я хотел именно разделить два подхода, для этого требовалось два TradeDefinition класса для каждого из подходов и конвертер должен был уметь принимать их оба. Можно было бы и у них наследование сделать, но хотелось их попроще сделать, это жеж просто data class.

2019-10-14 22:47 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/Converter.java
> +    public AbstractTrade convertApiToData(TradeDefinition tradeDefinition) {
Можно, но хотелось TradeDefinition оставить просто data class'ом без какой либо логики.

2019-10-14 22:49 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    public AbstractTrade(Integer price) {
К сожалению, нет
https://stackoverflow.com/a/29771875

2019-10-14 22:49 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +    private final Integer price;
Описал выше, это может привести к потенциальным проблемам

2019-10-14 22:54 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach2/model/ITradeCreator.java
> +public interface ITradeCreator {
Почитал, и правда не используется)

2019-10-14 22:56 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +@Value
Получается некоторая дубликация, но в данном случае, мне кажется, лучше оставить, т.к. может озадачить кого-нибудь кто будет смотреть этот код и не знать о таком поведении @Value

2019-10-14 22:57 UTC, anatolyburtsev commented on build.gradle
> +    testImplementation('org.junit.jupiter:junit-jupiter:5.5.+')
ок

2019-10-14 22:58 UTC, anatolyburtsev commented on build.gradle
> +sourceCompatibility = 1.12
ok

2019-10-14 22:59 UTC, anatolyburtsev commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-all.zip
Idea автоматически сгенерила такой. Обновлю

2019-10-14 23:00 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach2/model/ITradeCreator.java
> +package ca.trade.approach2.model;
в approach1 - работающая версия для первого подхода. 
в approach2 - типа diff'a, что нужно заменить в первом.

2019-10-14 23:00 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/Service.java
> +public class Service {
согласен

2019-10-14 23:03 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/Converter.java
> +    public AbstractTrade convertApiToData(TradeDefinition tradeDefinition) {
В данном случае API - это чтение из файла. 
model/api/TradeDefinition.java - представляет из себя входной формат, поэтому и здесь API в названии. 
Гипотетически сюда может добавиться метод convertDataToApi.
название да, согласен, переименую

2019-10-15 18:06 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/exceptions/IncorrectInputDataException.java
> +public class IncorrectInputDataException extends RuntimeException {
хорошее правило не делать пока не надо(yagni).  если понадобится, можно добавить.

2019-10-15 18:06 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    private final Integer price;
можно проверять в конструкторе, какое значение приходит. И как можно создать екземляр, а цену не поставить, если поле final ?

2019-10-15 18:06 UTC, alexmatorin commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +@Value
тогда почему @value, а не @data ?

2019-10-15 18:06 UTC, alexmatorin commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +    private final Integer price;
описал выше, что в конструкторе можно кидать ексепшен)

2019-10-15 18:06 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Main.java
> +        Service service = Service.builder()
yagni

2019-10-15 18:06 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/Converter.java
> +    public AbstractTrade convertApiToData(TradeDefinition tradeDefinition) {
лучше так не делать, но это отдельная тема)

2019-10-15 18:06 UTC, alexmatorin commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    public AbstractTrade(Integer price) {
проверил, у меня компилируется и работает

2019-10-21 02:19 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/exceptions/IncorrectInputDataException.java
> +public class IncorrectInputDataException extends RuntimeException {
Убрал кастомные, заменил на стандартные

2019-10-21 02:21 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/Main.java
> +        Service service = Service.builder()
заменил на коструктор

2019-10-21 02:26 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    private final Integer price;
проверил, да, так не выйдет. Заменил на int без NonNull

2019-10-21 02:27 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +    private final Integer price;
Заменил на int

2019-10-21 02:29 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach2/model/TradeDefinitionEnhanced.java
> +@Value
пересмотрел класс. От @value нужен только @Getter, на него и заменил.

2019-10-21 02:42 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/model/trade/AbstractTrade.java
> +    public AbstractTrade(Integer price) {
и правда работает. Заменил

2019-10-21 02:50 UTC, anatolyburtsev commented on src/main/java/ca/trade/approach1/Converter.java
> +    public AbstractTrade convertApiToData(TradeDefinition tradeDefinition) {
Ок, перенес в TradeDefinition, удалил Converter

2019-10-21 03:02 UTC, anatolyburtsev commented on src/test/java/ca/trade/TradeTestFixture.java
> +public class TradeTestFixture {
убрал

2019-10-21 18:00 UTC, merged